In [1]:
import  numpy as np
import pandas as pd
from importlib import reload
import bayes
reload(bayes)
import time
#import simuls, utils 
from tqdm.notebook import tqdm
from simuls import *
from utils import *
import statistics as st

In [2]:
data = ExampleOne(n = 60, sig = 1, with_test = True, seed = 1).data
data.to_df()
data.train.to_df(); data.test.to_df()
cols = [col for col in data.df.columns if "x" in col]

In [6]:
scores = {"mse":[], "corr":[]}
start = time.time(); n_iter = 100
for i in tqdm(range(n_iter)):
    data = ExampleThree(n = 200, sig=10, with_test = True, seed = i + 1).data
    #data.train.to_df(); data.test.to_df()
    yt = data.test.y; X_ = data.test.X 
    model = bayes.Wayfay(nIter=100, ld0 = 1, d0 = 1, eps=1/10000)
    model.fit(data.train.y, data.train.X) 
    BM = model.variables["B"].storage
    gam = model.gammas.storage.mean(axis=0) 
    B = BM.mean(axis=0)
    preds = dot(X_, B)
    sc = mse(preds, yt) ; print(sc)
    scores["mse"] += [sc]
    scores["corr"] += [np.corrcoef(preds, yt)[0,1]]
end = time.time() - start 
df = pd.DataFrame(scores)
print(df)
#res_df.to_csv("Data/Ex3_100_1_bis.csv")



  0%|          | 0/100 [00:00<?, ?it/s]

165.29428
146.21793
130.79809
143.62855
128.52132
175.56399
166.81879
231.87732
151.02485
136.74217
224.28449
125.32775
180.39652
152.6053
156.62622
169.80254
243.27263
169.21455
144.24697
172.3199
189.70293
167.57961
123.40841
135.98782
210.81863
141.43664
190.42123
163.57871
185.37964
207.94856
184.96055
142.03944
204.35994
137.43151
200.23832
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
173.70777
195.87168
174.87772
!!! BOOM !!!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [7]:
df.mean()

mse     168.402405
corr      0.578719
dtype: float64

In [8]:
scores = {"mse":[], "corr":[]}
start = time.time(); n_iter = 100
for i in tqdm(range(n_iter)):
    data = ExampleThree(n = 400, sig=10, with_test = True, seed = i + 1).data
    #data.train.to_df(); data.test.to_df()
    yt = data.test.y; X_ = data.test.X 
    model = bayes.Wayfay(nIter=100, ld0 = 1, d0 = 1, eps=1/10000)
    model.fit(data.train.y, data.train.X) 
    BM = model.variables["B"].storage
    gam = model.gammas.storage.mean(axis=0) 
    B = BM.mean(axis=0)
    preds = dot(X_, B)
    sc = mse(preds, yt) ; print(sc)
    scores["mse"] += [sc]
    scores["corr"] += [np.corrcoef(preds, yt)[0,1]]
end = time.time() - start 
df = pd.DataFrame(scores)
print(df)
#res_df.to_csv("Data/Ex3_100_1_bis.csv")



  0%|          | 0/100 [00:00<?, ?it/s]

!!! BOOM !!!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1.]
124.02177
!!! BOOM !!!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1.]
106.80406
!!! BOOM !!!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1.]
145.72532
!!! BOOM !!!


In [9]:
df.mean()

mse     113.111992
corr      0.705297
dtype: float64

In [26]:
scores = {"mse":[]}
start = time.time(); n_iter = 100
for i in tqdm(range(n_iter)):
    data = ExampleSelectOne(n = 60, sig=1, with_test = True, seed = i + 1).data
    #data.train.to_df(); data.test.to_df()
    yt = data.test.y; X_ = data.test.X 
    model = bayes.Wayfay(nIter=100, ld0 = 1, d0 = 1, eps=1/10000)
    model.fit(data.train.y, data.train.X) 
    md = st.mode(model.gammas.storage.sum(1))
    gam = model.gammas.storage.mean(axis=0)  #> 0.5
    argz = np.argsort(gam)[-int(md):]
    gam = np.zeros_like(gam)
    gam[argz] = 1; #print(gam, md)
    tg = data.betas > 0; 
    sc = (gam == tg).all() 
    scores["mse"] += [sc]
    #scores["corr"] += [np.corrcoef(preds, yt)[0,1]]
end = time.time() - start 
df = pd.DataFrame(scores)
print(df)
#res_df.to_csv("Data/Ex3_100_1_bis.csv")



  0%|          | 0/100 [00:00<?, ?it/s]

      mse
0   False
1   False
2   False
3   False
4   False
..    ...
95  False
96  False
97  False
98  False
99  False

[100 rows x 1 columns]


In [27]:
df.mean()

mse    0.0
dtype: float64

In [36]:
scores = {"mse":[]}
start = time.time(); n_iter = 100
for i in tqdm(range(n_iter)):
    data = ExampleSelectOne(n = 240, sig=5, with_test = True, seed = i + 1).data
    #data.train.to_df(); data.test.to_df()
    yt = data.test.y; X_ = data.test.X 
    model = bayes.Wayfay(nIter=250, ld0 = 1, d0 = 1, eps=1/100)
    model.fit(data.train.y, data.train.X) 
    gam = model.gammas.storage.mean(axis=0)  > 0.5
    tg = data.betas > 0; 
    sc = (gam == tg).all() 
    scores["mse"] += [sc]
    #scores["corr"] += [np.corrcoef(preds, yt)[0,1]]
end = time.time() - start 
df = pd.DataFrame(scores)
print(df)
#res_df.to_csv("Data/Ex3_100_1_bis.csv")



  0%|          | 0/100 [00:00<?, ?it/s]

!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0. 0. 0. 0. 0.]
!!! BOOM !!!
[1. 0. 0. 0.

In [38]:
df.mean()

mse    0.6
dtype: float64